Bug: Remove '%' character from argparse option
Running python curate_vocab.py -h in its current form throws an error:

    TypeError: %o format: a number is required, not dict

This seems to be due to the '%' character in one of the help options.
Somewhere argparse is trying to do string-formatting which is
unintended.